 on:
    workflow_dispatch:
#   schedule:
#     - cron: "*/5 * * * *"

name: generate-translations

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    env:
      REPO_KEY: ${{ secrets.REPOS_KEY }}
      WEBLATE_KEY: ${{ secrets.WEBLATE_KEY }}
      QML_REPO: jasptestmodule-qml
      R_REPO: jasttestmodule-r

    steps:
      - uses: jasp-stats/jasp-actions/wlcLock@master

      - uses: jasp-stats/jasp-actions/translations@master
